### ISSUE TITLE
'start' not defined

### ISSUE THREAD

**Issue by Greatnessguru** [snowka/picosystem#1]
main.py output:
Traceback ...:
File "main.py", line 215, ...
NameError: name 'start' is not defined
Code done running

I'm using CircuitPython 7.3.0.
https://circuitpython.org/board/pimoroni_picosystem/

**Comment by snowka** [comment]
My program assumes that you are using the picosystem Micropython firmware rather than CircuitPython. 
See https://shop.pimoroni.com/products/picosystem?variant=32369546985555 and
https://github.com/pimoroni/picosystem/releases

With Micropython installed the start() function should run.

**Comment by Greatnessguru** [comment]
Thanks for responding. Is it possible to port this code to CircuitPython?
Would it be very much trouble?

**Comment by snowka** [comment]
I don't think so. My code was based on the functions found in the demo software for the Micropython firmware for Picosystem, but the program itself is fairly basic. You would just have to determine if there are different functions in CircuitPython for drawing to the screen than the ones I use in my program. Otherwise, I think that the program is pretty straightforward Python.

**Comment by Greatnessguru** [comment]
Thanks. I installed the Pimoroni Micropython, copied the code and ran the code just fine.
I'll see if I want to try porting it to CircuitPython. Would be nice. Thanks again.
